server:
  port: ${APP_PORT:8080}

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin
    hikari:
      pool-name: H2-HikariPool
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail: # Gmail Configuration
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, ${spring.profiles.active}]'
  file:
    name: ${LOG_PATH:.}/mail-app.log

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Mail Application
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom