server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail: # Gmail Configuration
    host: smtp.gmail.com
    port: 587
    username: vedha@gmail.com
    password: app-key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

SPRING_BOOT: Application Properties

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot Mail Application
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom